# Generated by Django 4.2 on 2025-07-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_requestlogs_request_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlogs',
            old_name='request_type',
            new_name='request_path',
        ),
    ]
